# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_DOMAIN: ${{ secrets.TEST_DOMAIN }}
      TEST_SUBDOMAIN: ${{ secrets.TEST_SUBDOMAIN }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies on AdvancedBilling
      run: dotnet restore AdvancedBilling.sln
    - name: Build AdvancedBilling
      run: dotnet build AdvancedBilling.sln --no-restore
    - name: Restore dependencies on AdvancedBilling Tests
      run: dotnet restore AdvancedBillingTests.sln
    - name: Test
      run: dotnet test AdvancedBillingTests.sln --verbosity normal
